### ISSUE TITLE
Is it possible to overlap items?

### ISSUE THREAD

**Issue by Giosk** [crosswall/Android-Coverflow#1]
Hi Crosswall,
 you did a great library and probably you saved a lot of time to me.
Is it possible to customize the CoverFlow.Builder() and adding the option for items overlapping?
I'm trying to do something like the attached image.

![issue-crosswall](https://cloud.githubusercontent.com/assets/8496187/15041789/0aa0850c-12bf-11e6-8795-f5a8196cf114.png)

Thanks
Giosk

**Comment by crosswall** [comment]
I can try, but I need a little more time 

Maybe you can use this [CarouselLayoutManager](https://github.com/Azoft/CarouselLayoutManager)

**Comment by Giosk** [comment]
Ok I'll try [CarouselLayoutManager](https://github.com/Azoft/CarouselLayoutManager) but you did a great job and I prefer your solution. :-)

**Comment by vincent-paing** [comment]
I really do need this function too

**Comment by vincent-paing** [comment]
Hello @crosswall , I have created a pull request with settings for Overlapping.
