### ISSUE TITLE
两边的那个可以改变凹陷的方向吗，你是往里进，我想调整一下，另外变翘起

### ISSUE THREAD

**Issue by catroom** [crosswall/Android-Coverflow#13]
相当于不放大的另外两个改变翘起方向

**Comment by crosswall** [comment]
设置scale 和 rotate试试看吧

**Comment by catroom** [comment]
我设置315度就改变方向了，但是滑动的时候，翻的太厉害，可能我要在优化一下了。。可能要改源码了

**Comment by crosswall** [comment]
滑动速度貌似我写了一个[CustomScroller](https://github.com/crosswall/Android-Coverflow/blob/master/coverflow/src/main/java/me/crosswall/lib/coverflow/core/CustomScroller.java)控制，你看看对你有没有用

**Comment by catroom** [comment]
我的是旋转的太厉害了。不知道现在为什么会滑动的时候会黏在一起，要再划一下才不会黏在一起

**Comment by catroom** [comment]
情况是我向右划一下应该可以翻了，但是左边黏在一起，再轻微划一下才不会黏在一起
