### ISSUE TITLE
能否提供一个onItemClcikListener的接口,能否提供一个

### ISSUE THREAD

**Issue by zj8331182** [crosswall/Android-Coverflow#14]
如题,目前没有onItemClick 和OnItemLongClick接口

**Comment by crosswall** [comment]
好的，有时间会弄的。

目前你可以通过触摸区域来判断item的点击，会尽快更新的。
pagerContainer.setOnTouchEvent(...)

**Comment by zj8331182** [comment]
good job

**Comment by haemi** [comment]
unfortunately I don't understand the chinese part here :) how is it possible to determine which item was tapped on?

**Comment by zj8331182** [comment]
Yes, the chinese part means 'there is no such methods like onItemClickListener and onItemLongClickListener'

**Comment by crosswall** [comment]
coming soon...@zj8331182 @haemi

**Comment by crosswall** [comment]
@zj8331182 @haemi see [Demo](https://github.com/crosswall/Android-Coverflow/blob/master/app/src/main/java/me/crosswall/coverflow/demo/NormalActivity.java#L36-L41)
