### ISSUE TITLE
有没人像我一样一边黏住的效果

### ISSUE THREAD

**Issue by catroom** [crosswall/Android-Coverflow#16]
就嵌套了一个下拉刷新就一边黏住了。。很影响用户体验，希望博主能看到

**Comment by crosswall** [comment]
滑动冲突吗？建议你处理touch事件

**Comment by catroom** [comment]
adapter.notifyDataSetChanged();
        pager.setAdapter(adapter);
        pager.setOffscreenPageLimit(adapter.getCount());
        // 设置一个监听器，当ViewPager中的页面改变时调用
        pager.addOnPageChangeListener(this);
        pager.setClipChildren(false);
        new CoverFlow.Builder()
                .with(pager)
                .scale(0.2f)//放大缩小倍数
                .pagerMargin(0f)//每页之间的间距
                .spaceSize(2f)
                .rotationY(315f)//旋转角度
                .build();
我是直接这么用啊，嵌套冲突解决了还是这样。因为我也找不到什么原因。

**Comment by catroom** [comment]
现在这样的情况，应该是可以不可见的情况，第一次初始化的时候我有四张，他会先平黏在一起，然后立刻可以凹进去，但是之后向右滑动第三张从不可见到可见就黏在一起了。。。

**Comment by crosswall** [comment]
你能发个你司产品的设计稿吗

**Comment by catroom** [comment]
pager.setOffscreenPageLimit(3);//好重要的地方啊
搞定了，因为我之前一直是用的adapetr.getCount。我设置为3.就不会黏住了，谢谢了。
