### ISSUE TITLE
The method of setPageItemClickListener not work

### ISSUE THREAD

**Issue by linkenghong** [crosswall/Android-Coverflow#35]
In the demo,the following code doesn't work,when I click the item,it doesn't pop-up.
I want to know if it's my method or the code itself is wrong.
Thank you!
```
        container.setPageItemClickListener(new PageItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
                Toast.makeText(NormalActivity.this,"position:" + position,Toast.LENGTH_SHORT).show();
            }
        });
```

**Comment by linkenghong** [comment]
I find it will pop-up if I click the location below the item,but I hope it will also pop-up if I click on the item.

**Comment by linkenghong** [comment]
I find the way to implement with the follow code:
```
//MyPagerAdapter
public Object instantiateItem(ViewGroup container, int position) {
    View view = LayoutInflater.from(NormalActivity.this).inflate(R.layout.item_cover,null);
    view.setOnClickListener(new View.OnClickListener() {
       @Override
       public void onClick(View v) {
              ...
        }
      });
      ...
}
```

**Comment by RobMans426** [comment]
@linkenghong Hi, I faced same issue. I implemented onClickListener inside adapter. but it still not working. could you let me know how did you solve this problem? Best Regards.
